CREATE TABLE `OILPRICES` (
  `RecordID` int NOT NULL AUTO_INCREMENT,
  `TimeReading` time DEFAULT NULL,
  `DateReading` date DEFAULT NULL,
  `OilPrice` float DEFAULT NULL,
  `OILTYPE` enum('BRENT','WTI','MURBAN') DEFAULT NULL,
  PRIMARY KEY (`RecordID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci