CREATE TABLE `OILPRICES` (
  `RecordID` int PRIMARY KEY AUTO_INCREMENT,
  `OilID` INT,
  `Price` FLOAT,
  `OilPrice` float DEFAULT NULL,
   FOREIGN KEY (OilID) REFERENCES OILTYPE(OilID)
   
) ENGINE=InnoDB AUTO_INCREMENT=89 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci