CREATE TABLE READING(
	DatapointID INT PRIMARY KEY AUTO_INCREMENT,
    TimeReading TIME,
    MarketDate DATE

);

CREATE TABLE OILTYPE(
	OilID INT PRIMARY KEY AUTO_INCREMENT,
    OilName VARCHAR(10)
);

INSERT INTO OILTYPE(OilName)
VALUES ("WTI"),
("BRENT"),
("MURBAN");


CREATE TABLE OILPRICES(
	RecordID INT PRIMARY KEY AUTO_INCREMENT,
    DatapointID INT,
    OilID INT,
    Price FLOAT,
    FOREIGN KEY (DatapointID) REFERENCES READING(DatapointID),
    FOREIGN KEY (OilID) REFERENCES OILTYPE(OilID)
);
